name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
      - master
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
      - master

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false

      # Setup Node.js v20 to meet dependency requirements
      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      # Install root dependencies
      - name: Install root dependencies
        run: npm ci

      # Install backend dependencies
      - name: Install backend dependencies
        run: |
          cd backend
          npm ci --omit=dev

      # Install project dependencies with proper vite installation
      - name: Install project dependencies
        run: |
          cd project
          npm ci
          # Ensure vite is properly installed
          npm install vite@latest --save-dev

      # Build the application
      - name: Build application
        run: npm run build:all

      # Deploy to Azure Static Web Apps
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "project/dist" # Built frontend location (no leading slash)
          api_location: "backend" # Backend API location (no leading slash)
          output_location: "dist" # Built app content directory
          skip_app_build: true # Skip build since we already built with npm run build:all

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "close"